version: '3.7'

services:
  stan-nats:
    image: nats-streaming:latest
    container_name: stan-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [
      "-p", "4222",
      "-m", "8222",
      "-store", "file",
      "-dir", "/data",
      "-cid", "my-cluster"
    ]
    volumes:
      - ./nats/data:/data

  db_employees:
    image: postgres
    container_name: db_employees
    restart: always
    environment:
      POSTGRES_DB: 'employees'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '123'
    volumes:
      - ./database/docker-entrypoint-initdb.d/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "9876:5432"
#
#  publisher:
#    build:
#      context: ./publisher
#      dockerfile: ./docker/Dockerfile  # Укажите путь к вашему Dockerfile
#
#    ports:
#      - 80:80
#
#  retrieval:
#    build:
#      context: ./retrieval
#      dockerfile: ./docker/Dockerfile  # Укажите путь к вашему Dockerfile
#
#    ports:
#      - 70:70

  reader:
    build:
      context: ./reader
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000