version: '3.7'

services:
  service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile  # Укажите путь к вашему Dockerfile

    ports:
      - 80:80

  stan-nats:
    image: nats-streaming:latest
    container_name: stan-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [
      "-p", "4222",
      "-m", "8222",
      "-store", "file",
      "-dir", "/data",
      "-cid", "my-cluster" # Установка имени кластера
    ]
    volumes:
      - ./data:/data